### ISSUE TITLE
[TextArea] initial component

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#138]
As a product developer, I want to use text areas in my product that follow the guidelines set by the CA Style Guide.

Link to styleguide: https://ca2.invisionapp.com/d/main#/console/11070131/235066870/preview

#### Design Questions
- text area size small (like textInput)
- read only with variant should not be colorized
- are icons allowed in text areas?

**AC:**
Schema for component considerations
Things needed for a "text area" component:

1. Typography
    - currently looks like Open Sans
    - system font fall back
    - need font-sizes to map to sizes
    - need weights
2. Color
    - should be a single style/color with states for error and other outliers
3. Spacing
    - map to same as button spacing
4. ~Icons~
    - n/a
5. Animation
    - not yet?
6. States
7. Size / Shape
8. Variants (kinds)
9. A11y
10. Development Docs (props, code, examples)
11. Design Docs (usage, philosophy, patterns)

**Considerations:**

We should probably think about what an MVP of this component is.

**Comment by brentertz** [comment]
Sorry, I just noticed this after creating #507.  Closing this one as a duplicate.
