### ISSUE TITLE
[Website] Card and ComponentUtils pages borked on mobile

### ISSUE THREAD

**Issue by brentertz** [mineral-ui/mineral-ui#190]
### Expected behavior

Pages should layout correctly on mobile devices and/or at small screen sizes.

### Current behavior

The Card and ComponentUtils pages layout incorrectly.

 ![](http://g.recordit.co/CjBpkVeCv8.gif)

### Possible solution

Be more responsive.

### Steps to reproduce (for bugs)
1. Visit aforementioned pages on http://mineral-ui.com using a mobile device or with a small screen resolution.  Chrome dev tools with the device toolbar turned on works well.

### Context

Looks unsightly, unprofessional, and is less usable.

### Versions
| Component | Version |
| :-------- | :------ |
| Site | 0.6.1 |

**Comment by coldpour** [comment]
looks like this was fixed during the great website redesign of 2017, probably [PR-460](https://github.com/mineral-ui/mineral-ui/pull/460)
