### ISSUE TITLE
[Component Strategy] Spike Implementation

### ISSUE THREAD

**Issue by brentertz** [mineral-ui/mineral-ui#21]
As a Mineral UI developer, I want to investigate possible implementations for future development of components and styles, so that we provide components that meet consumers needs and are maintainable.

**AC:**

- Investigate leading solutions
  - styled-components
  - glamorous
  - fela
  - other?
- Experiment with code in mineral-ui
  - abstract underlying implementation so that css-in-js solution may be swapped
  - base components
  - public props API
  - themes
  - DX
    - debugging styles
    - HMR
  - writing tests
    - including snapshot tests
  - Requirements placed on consuming app

**Considerations:**

- See document for considerations
https://docs.google.com/document/d/1uQYXaQhiioUCzcIgjZxWXeM7jzpgmVRy1We6wwSlEp4

**Comment by kylegach** [comment]
Findings are documented here: https://github.com/mineral-ui/mineral-ui/blob/master/docs/discussions/styling.md
