### ISSUE TITLE
[Component Strategy] Recommendations

### ISSUE THREAD

**Issue by brentertz** [mineral-ui/mineral-ui#22]
As a Mineral UI developer, I want to investigate possible implementations for future development of components and styles, so that we provide components that meet consumers needs and are maintainable.

**AC:**

- Discuss recommendations with consumers and gather consensus
- Write up a research results document

**Considerations:**

- See document for considerations and recommendations
https://docs.google.com/document/d/1uQYXaQhiioUCzcIgjZxWXeM7jzpgmVRy1We6wwSlEp4

**Comment by coldpour** [comment]
We've created a doc with our [styling and theming recommendations](https://github.com/mineral-ui/mineral-ui/blob/master/docs/styling.md).
