### ISSUE TITLE
[Site] Map components onto Gatsby site

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#220]
As a user, I would like to see a list of components, a component page akin to what is in the site.

AC:
* list the components on the site
* Figure out a way to pull in published public packages in Mineral UI
* Generate links to navigate to component pages.
* URL remains the same
* Pages follow current styling

Other Considerations:
Merging two apps together
Flow is in one but not the other
Need to pair to better understand the current site

**Comment by riley** [comment]
this is complete with https://github.com/mineral-ui/mineral-ui/pull/256
