### ISSUE TITLE
button: Missing documentation to install @mineral-ui/component-utils

### ISSUE THREAD

**Issue by calthomson** [mineral-ui/mineral-ui#242]
### Expected behavior
Expected to be able to follow documentation and import Mineral-UI Button into my project.

### Current behavior
Get the error 'can't resolve @mineral-ui/component-utils'

### Possible solution
Add instruction to documentation:
`npm install --save @mineral-ui/component-utils`

### Steps to reproduce (for bugs)
1. Clone mineral-ui component repository
2. Follow import instructions

### Context
Trying to use mineral-ui Button in a project

### Versions
| Button | 2.0.1 |

**Comment by coldpour** [comment]
Some possible solutions:

* Update package readmes to include "Install the package and any of its peer dependencies"
* Add a dev time check for components that validates that they are being used inside of a ThemeProvider?
* update package readmes with script that installs peer dependencies
