### ISSUE TITLE
button: Missing styling

### ISSUE THREAD

**Issue by calthomson** [mineral-ui/mineral-ui#244]
### Expected behavior
* Button component should have default styling

### Current behavior
* Button component's styling does not match the styling in the [Mineral-UI documentation](http://mineral-ui.com/components/button)

![screenshot 2017-08-08 16 00 57](https://user-images.githubusercontent.com/8645285/29098283-806826c4-7c53-11e7-82d7-6098a64a3ceb.png)

### Steps to reproduce (for bugs)
1. Import Mineral-UI button component into a react project
2. Instantiate regular, primary and minimal buttons within application
Observe that the stylings do not match those in the documentation.

### Context
* Trying to use the Mineral-UI button in our Phoenix-Dashboard project

### Versions
| Button | 2.0.1 |

**Comment by coldpour** [comment]
@calthomson, it looks like you are missing the ThemeProvider. That should provide all the style variables on React’s context similar to how React Router works. Our [README](https://github.com/mineral-ui/mineral-ui/blob/master/README.md) explains this briefly,
and our [style doc](https://github.com/mineral-ui/mineral-ui/blob/master/docs/styling.md#themeprovider-theme) explains it in a bit more detail. You can put a ThemeProvider at any level of your JSX hierarchy, even at multiple levels, and you should see the styles applied accordingly
