### ISSUE TITLE
[Button] Icon not vertically centred with text

### ISSUE THREAD

**Issue by calthomson** [mineral-ui/mineral-ui#253]
### Expected behavior
* Expected icon to be vertically centred with Button text

### Current behavior
* Icon is not vertically centred with Button text

### Steps to reproduce (for bugs)
1. Instantiate a Button with both text and an icon with height shorter than the height of the text
Observe that the icon floats at the top of the text rather than being vertically centred alongside it:

![screenshot 2017-08-10 17 40 15](https://user-images.githubusercontent.com/8645285/29197786-4453a27a-7df3-11e7-89d9-62ba736c2cd7.png)

### Context
* Using the Button component with an Icon in our Phoenix-Dashboard project

### Versions
| Button | 2.0.1 |

**Comment by kylegach** [comment]
Hi, Caledonia. Can you please provide the code of your Button with the issue? Something like... `<Button iconStart={<IconCloud />} size="jumbo">Jumbo</Button>`.

**Comment by calthomson** [comment]
<Button primary iconStart={uploadIcon(classes)} classes={classes.uploadFaviconButton}>
Upload Favicon
</Button>

Where uploadIcon is a function that returns an Icon component

**Comment by kylegach** [comment]
Thanks!

Unfortunately, I still can’t tell what’s causing the issue. Is your repo public or on CA’s Enterprise GitHub?

If your repo isn’t sharable, I’m guessing it has to do with whatever the `classes` prop is doing.

**Comment by calthomson** [comment]
This issue is not specific to my use case. If you go to http://mineral-ui.com/components/button and make the size of the icon in the example buttons smaller, say 5px, the Icon will also not be vertically centred alongside the text. The screenshot I included in this issue is from me doing that.

**Comment by asagray** [comment]
@calthomson Can you show a design example where a shrunk icon is desirable? That currently isn't planned for the design spec.

**Comment by Mikewaite** [comment]
As long as we support passing in your own SVG's this is a problem we should fix, which sounds pretty easy. In the future when we have a style guide made public, it will be strongly encouraged to follow those guidelines.

Nice bug catch @calthomson

**Comment by calthomson** [comment]
@asagray I agree that a shrunken icon is not a normal design choice. Here is a quick example of what I am seeing for my current Button:

Current:
![screenshot 2017-08-17 12 38 21](https://user-images.githubusercontent.com/8645285/29431494-f53e3db2-834c-11e7-9b6c-f4ade5f68285.png)

Desired (`align-items: center` added):
![screenshot 2017-08-17 12 37 53](https://user-images.githubusercontent.com/8645285/29431498-f8a38a84-834c-11e7-833b-4209a5326e27.png)

@Mikewaite Thanks!

**Comment by kylegach** [comment]
Just opened a PR with a fix. Thanks for making us aware!

**Comment by kylegach** [comment]
@calthomson — This fix was just released with Button 4.0.2.
