### ISSUE TITLE
[Link] Required module not found for '@mineral-ui/link'

### ISSUE THREAD

**Issue by calthomson** [mineral-ui/mineral-ui#281]
### Expected behavior
* Expected that I could use the Mineral-UI Link component by running `npm install --save @mineral-ui/link` and importing (`import Link from '@mineral-ui/link'`) the link component in my file.

### Current behavior
* Getting **Required module not found** error for the '@mineral-ui/link' module.

### Possible solution
* Not sure

### Steps to reproduce (for bugs)
1. `npm install --save @mineral-ui/link`
2. Import (`import Link from '@mineral-ui/link'`) Link component into file
* Note that there are **Required module not found** errors regarding the '@mineral-ui/link' module

I've made a PR [here](https://github-isl-01.ca.com/APIM-WEB/Phoenix-Dashboard/pull/6) where you can see how I've tried to use the Link component.

### Context
* Trying to use the Link component in our Phoenix-Dashboard project

### Versions
| Link | 2.0.0 |

**Comment by kylegach** [comment]
Hi, @calthomson.

I could use Link in both a local create-react-app sandbox as well as here: https://codesandbox.io/s/6jlv79y1pr

Can you share the exact error message you’re seeing, please?

**Comment by calthomson** [comment]
No longer getting this error, not sure why, but I'll close the bug! 

Thanks

**Comment by calthomson** [comment]
Realized that this bug is in fact still showing up. The original PR I posted of the branch where the bug can be seen is still available [here](https://github-isl-01.ca.com/APIM-WEB/Phoenix-Dashboard/pull/6). Based on that PR, am I missing something?

**Comment by coldpour** [comment]
determined to be an issue with our flow types. we're not publishing them as part of our new packages. suggested fix: upgrade to mineral-ui library instead of individual component packages.
