### ISSUE TITLE
[Icon] extract into separate package

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#315]
As a mineral-ui developer, I would like to extract `mineral-ui-icons` to a separate npm package, so that the build is faster.

As a mineral-ui consumer, I would like `mineral-ui-icons` to be available as a separate npm package, so that
* I can choose to import them or not
* It is less likely that I accidentally import all of them if my tree shaking setup is wonky

**AC**

* Extract icons to separate npm package, inside mineral-ui/packages folder
* Script and/or documentation on how to publish mineral-ui-icons package
* Continue to provide Icon component in mineral-ui package, but without prepackaged icons
* Update website documentation
    * In docs for Icon component, describe how to import other icons from mineral-ui-icons package
    * TBD: How to best document available icons

**Other considerations**

* Rename generated icons to remove the Icon keyword - easier match, users can rename on import, more flexible
* Consider renaming to SvgIcon for clarity and then could also consider providing FontIcon in future

**Comment by brentertz** [comment]
Work has been started on [315-mineral-ui-icons](https://github.com/mineral-ui/mineral-ui/tree/315-mineral-ui-icons) branch, but there is not enough time to complete it at present.
