### ISSUE TITLE
fix minimum React peer dependency version

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#353]
`package.json` currently lists react as a peer dependency and requires anything greater than v15.0.0.  This is not likely accurate and our minimum version is likely higher than this.

AC:

* React peer dependency in package.json is updated to minimum supported version

**Comment by brentertz** [comment]
Reopening: I had merged a PR to update the minimum version to `15.6.1`, just playing it safe, but now that I have done more testing, I believe the minimum version to be `15.3.0`.  I will open another PR to update the version separately.
