### ISSUE TITLE
[Tooltip] component

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#356]
As a product developer, I want to use tooltips in my product that follow the guidelines set by the CA Style Guide so that I can provide contextual help to my users.

#### AC
1. follows [styling spec](https://ca.invisionapp.com/d/main#/console/11070131/250301217/preview)
2. same placement options as popover
3. content limited to a string (or function returns string)
6. A tooltip is a popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it. It typically appears after a small delay and disappears when Escape is pressed or on mouse out.
7. Tooltip widgets do not receive focus. A hover that contains focusable elements can be made using a [non-modal dialog](https://www.w3.org/TR/wai-aria-practices/#tooltip).
8. The element that serves as the tooltip container has role tooltip.
9. The element that triggers the tooltip references the tooltip element with aria-describedby.
10. controlled & uncontrolled

#### Considerations
* just doing with CSS may not be accessible
* what is the cost of styling the Popover like a tooltip?
* trigger on hover/focus (and onClick?, multiple simultaneous)
* long press on mobile (1500ms)
* rtl affects placement?
* should not need to stay open for interactions - use popover
* render placement portal/sibling

#### Other tooltips
* https://atlassian.design/guidelines/product/components/tooltips
* http://blueprintjs.com/docs/#core/components/tooltip
* https://material.io/guidelines/components/tooltips.html
* https://material-ui-next.com/demos/tooltips/
* https://developer.microsoft.com/en-us/fabric#/components/tooltip
* https://vmware.github.io/clarity/documentation/tooltips
* http://carbondesignsystem.com/components/tooltip/code
* https://www.lightningdesignsystem.com/components/tooltips
* https://polaris.shopify.com/components/overlays/tooltip#navigation
* https://www.predix-ui.com/#/elements/px-tooltip

**Comment by coldpour** [comment]
http://356-tooltip--mineral-ui.netlify.com/components/tooltip/
