### ISSUE TITLE
[Theme] structural improvements

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#376]
As a developer, I want a logical, understandable system defining the name and use of our theme variables.

AC:
1. All current use cases considered and accounted for
2. Reasonable effort to consider future use cases
3. If not already done in #365, add all icons used by components as theme variables

**Comment by kylegach** [comment]
For potential reference:

![pasted_image_at_2017_09_29_09_45_am.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5914e6a59a500a0020614947/125516c66e82c728ace21e0d46f895893787879686e4be44a162f180161477227e3bf3724fd7ba17ef1b44555a301ff153444d04bea6d37ef5f22e7a985902ecd53c0c77c46e19febb8518bf01b923dd4987e2eddf5edcfa7f74b9dfd0126754505a9bf54f34a8934acd58f042e64855a4113664e5647b.png)

**Comment by Mikewaite** [comment]
Closing as we cover most of this in #570
