### ISSUE TITLE
[Dropdown] [Popover] Critical follow-up

### ISSUE THREAD

**Issue by kylegach** [mineral-ui/mineral-ui#382]
As a consumer, I want Dropdown to match spec and have full, proper support for the following, so that it meets my needs.

AC:
1. Dropdown matches latest spec
    * Notably, top/bottom space in the menu should be removed
* A11y
    * arrow up/down does not work in voiceover mode when using keyboard to open button (when trigger is not focused)
        * Possible solution:
            * If focused trigger onOpen, aria nav would probably work
            * Probably bad for when component is controlled, but might be okay
    * Improve AT announcing
        * Introduces i18n accountability
            * Announcer
                * 1. From a11y Slack:

                   > something to keep in mind for react apps is that you may want to use `shouldComponentUpdate` to prevent the live region from being re-rendered if the text hasn’t changed. Otherwise screen readers will keep reading it repeatedly for every render cycle

* restoreFocus paradigm needs investigation
    * Possible solution: skip restoreFocus if click outside component
    * To illustrate, put a Popover and a Dropdown on the same page, open one, then click the trigger of the other. Notice that the one you first opened steals focus from the newly-opened one.
    * Also affects Popover

**Comment by brentertz** [comment]
Combined into #366 as the changes are very interrelated.  Will split out individual stories if needed.
