### ISSUE TITLE
CardBlock: How to adjust left and right padding

### ISSUE THREAD

**Issue by calthomson** [mineral-ui/mineral-ui#397]
### Expected behavior
I am using the CardBlock component in a case where the left and right padding is less than what the Mineral-UI CardBlock component has. I'm wondering what the best way to overwrite this padding is?

### Current behavior
Above is the tile using the CardBlock with the current padding, below is a screenshot of the tile from the designs.
![screen shot 2017-10-04 at 2 47 42 pm](https://user-images.githubusercontent.com/8645285/31201421-7a0d5b7c-a913-11e7-95ed-d6b61158689f.png)

### Possible solution
I'm trying to avoid using negative padding/margins.

### Context
Trying to use the CardBlock within our own custom tile component.

### Versions
| CardBlock | ^0.1.0 |

**Comment by coldpour** [comment]
Hey @calthomson, when we put in the Cards, we put a [ThemeProvider at the Root](https://github-isl-01.ca.com/APIM-WEB/Phoenix-Dashboard/blob/develop/src/app/containers/Root/index.js#L106) of the app and set up some theme variable overrides in there to bump up the padding, on [line 7](https://github-isl-01.ca.com/APIM-WEB/Phoenix-Dashboard/pull/15/files#diff-ab085fb1e68783bfe051751b5e9bc54aR7) and [line 8](https://github-isl-01.ca.com/APIM-WEB/Phoenix-Dashboard/pull/15/files#diff-ab085fb1e68783bfe051751b5e9bc54aR8) of [apimTheme.js](https://github-isl-01.ca.com/APIM-WEB/Phoenix-Dashboard/blob/develop/src/app/containers/Root/apimTheme.js). There are a couple options for how to remedy this depending on which situation you find yourself in.

If you don't need those overrides anymore, you can just delete them, and you'll fall back to the default mineralTheme values which are closer to 24px (in ems of course). If your icons/images need more padding around them to fit them into the card now with less padding, you can use [createStyledComponent](http://mineral-ui.com/components/utils/create-styled-component/) to make a little layout component that will contain your icon and it could even be display flex or use media queries or whatever. 

If you need two card components for different purposes with different amounts of padding in them, I'd recommend using [createThemedComponent](http://mineral-ui.com/components/utils/create-themed-component/) to create those two variations and use them in your specific places.

**Comment by calthomson** [comment]
Great, I've altered the `apimTheme.js` file to use the minimum amount of padding we need for tiles in our app and will add padding by passing the className prop where needed. 

Thanks for your help @coldpour !
