### ISSUE TITLE
[Dropdown][Menu][Icon] Design spec updated

### ISSUE THREAD

**Issue by asagray** [mineral-ui/mineral-ui#405]
Dropdown spec for menu item has been updated:
https://ca.invisionapp.com/d/main#/console/11070131/250301075/preview
https://ca.invisionapp.com/d/main#/console/11070131/250301074/preview

- 12pt spacing removed from spec and replaced with 16pt
- Icons for variants have been finalized

Icons are available in the project assets:
https://ca.invisionapp.com/d/main#/projects/prototypes/11070131/assets

**Comment by Mikewaite** [comment]
Closing for icon replacement issue.
