### ISSUE TITLE
[Site] IA for Component Page

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#41]
As a consumer, I would like the information about a component to be available and laid out in a helpful, understandable manner. 

AC:
1. Create an IA document and wireframe that demonstrates content strategy for a single component.
1. Documents have been reviewed by potential consumers.

**Comment by kylegach** [comment]
![Photo Jun 01, 11 37 21 AM.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5914e6a59a500a0020614947/125516c66e82c728ace21e0d46d89c95378dc3839ae7ff13f511b0c5780674246956f26b51a8a164fd507a0f0b0013f50b0d1d56f6eb8a29acb738798c5b03ebd46b5a77c43803b0aac25de05bef73cf5d8fa4b9834dc4b96e26e5d8871d3d19021889fc5e63a69b1f990de406.jpg)
![Photo Jun 01, 11 37 32 AM.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5914e6a59a500a0020614947/125516c66e82c728ace21e0d46d89c95378dc3839ae7ff13f511b0c5780674246957f16b51a8a164fd507a0f0b0013f50b0d1d56f6eb8b2dacb738798c5b03ebd46b5a77c23d03b0aac25de05bef73cf5d8fa4b9834dc4b96e26e5d8871d3d19021889fc5e63a69b1f990de406.jpg)

**Comment by kylegach** [comment]
Documented here: https://docs.google.com/document/d/1XbE_rDMXsp58RYCiZE6OlOrYSNJPo5kxMS_4OZNh3CQ/edit#heading=h.4fofgh8mqm9a

**Comment by kylegach** [comment]
And here’s that document represented visually:

![button-desktop-c](https://user-images.githubusercontent.com/486540/27448344-b926d91a-5741-11e7-9b09-78828dbfa618.png)

Think of this like a wireframe, meant to communicate hierarchy and layout, but not much else design-wise.
