### ISSUE TITLE
[Site] Site Map for Demo Site

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#43]
As a designer, I would like to know what pages, content and workflows I can expect from our demo site.

*AC:*
Create a sitemap that accounts for all the things listed in our card sorting exercise. Consider our user personas and create additional pages for their needs.

*Considerations*
Think about workflows from page to page to enhance the UX of our site.

**Comment by kylegach** [comment]
![Site map card sort result](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5914e6a59a500a0020614947/125516c66e82c728ace21e0d46d89c95378dc3839ae7ff13f511b0c6691477337a50e31b5dc7af6aad437505000217e6141a4d4eeefa8b21a7b235768d540de9d8645876ce2f0dbef8c040e554e964994597b3b58b4891bb3e27b483dd4c391905188afc0b33a2cd1a9d4abb.jpg)

**Comment by riley** [comment]
- list of pages that need to exist (in no particular order)
  - Theming instructions
  - Guidelines (usage)
  - Community (would love feedback on whether this should be MVP)
    - list of contributors
    - how to contribute
  - Getting Started
    - installation instructions
    - general summary of how the library is structured so consumers can easily discover features of mineral-ui
  - Home page
  - Component documentation
  - Resources (also on the "maybe" list)
- rough wireframes of layout
- list sections per page
- timeline for buildout

**Comment by riley** [comment]
Solicitation for feedback:

so a couple of notes here.
- Unless I'm missing something, the MVP could be boiled down to 2 pages, the home page and the docs pages.
- assuming the above, I think we could come up with some sort of Markdown > React solution that would save us a lot of time. Coding all of that would be a non-starter obvs.
    - the Components docs section is an obvious exception to the above.
    - kyle was saying he uses a markdown/react converter for his website, so I might steal that along with his expertise

![landing.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5968f8e8b328c1001f06992b/125516c66e82c728ace21e0d46e49594278b8daecda5fd53b652fa912a5265296b51fa7a2484e07bed4123035c5849ac415b5c12fafbdd7af3a42062c80d55b98e30063e937f03a6aa811eb500bf208b4c8cb7bf8b49c9e03e37aa.jpg)

![docs_page.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5968f8e8b328c1001f06992b/125516c66e82c728ace21e0d46ec9b9930bd93a888ecfd0fe64de29b234324676b5ee17e29d4b729bc112902570d4dab46585f47ffaf8f29f2e76962964e49bc8f3900299f7744eeaa880dbc00b0218e4f85b5b58b4fc2ef3d27e399c2.jpg)

**Comment by riley** [comment]
Mobile Docs pages

Notes:
- the lion's share of work here is going to be the Nav component. I'd like to have a discussion about where to put it in the queue.

#### Mobile Docs page
![mobile_docs.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5968f8e8b328c1001f06992b/125516c66e82c728ace21e0d46e59b982a8e86968be6bc50e611b2843b492d762a10e17132d0ba79eb4378525d0c46fe425f5844fcfa8a7da0b46821df4e17ff933c0120996048e6edc00db513b921814e80b6bc8e4cc0e93a24e58d885d73.JPG)

#### Mobile docs top-level menu
![mobile_docs-top-menu.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5968f8e8b328c1001f06992b/125516c66e82c728ace21e0d46e59b982a8e86968be6bc50e949ff84644b227d3c46ef696097ec22ba416f43554d4ba5405c0e17fffbda23f4b53b778a5c08ee876b5d20976803b0aac04ee155e57dd205d0f4ae805ec3e93724e28b8f4b3e1e04108cfd5535b2d4.JPG)

#### Mobile docs page-level
![mobile_docs-page-menu.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5968f8e8b328c1001f06992b/125516c66e82c728ace21e0d46e59b982a8e86968be6bc50e94df1932c0b2a762711e1673295f127b54778154d555ca948595b15affa8b78aee43f778d5c0beed23b5976926c44bea4905dee5fee7fd616cfe3fe9846d2eb3c2fe68e8f4f3a1e051980fa5c34a58b06.JPG)
