### ISSUE TITLE
[Website] live code box max height is too small

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#477]
it just needs to be a little taller

![Screen Shot 2017-11-14 at 2.21.44 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552ea384a95d40fb005e28ea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f76b7191a37af1102a4f5b5b5ecc3c4a4356bcbbd671f3e57862804e0ee4d0690e27c53f42a4ea8118b801ba23881983b4e8db19d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74be74451a11b366be5712431.png)

**Comment by kylegach** [comment]
Yeah, using that source as the max # of lines makes sense. Should be an easy change.
