### ISSUE TITLE
Enable node_modules caching in Travis

### ISSUE THREAD

**Issue by trotzig** [mineral-ui/mineral-ui#482]
While working on adding happo to the test suite (#474) I've noticed that it takes quite a while (up to 2 mins). I think you could benefit quite a bit from using the bundler caching feature in Travis: 
https://docs.travis-ci.com/user/caching/#Caching-directories-(Bundler%2C-dependencies)

tl;dr - "To use the caching feature, in your repository settings, set Build branch updates to ON."

**Comment by brentertz** [comment]
Agreed, we could probably get some build speed benefits here by caching `node_modules` in Travis. 

Being that we do not currently use a `package.lock`, I am a little concerned that updates to transitive dependencies might not get picked up, and our test suite might not catch something.  This happened to me just yesterday in a Netlify build.  

I need to revisit best practices surrounding `package.lock` files and libraries.

In the mean time, I have another [open PR](https://github.com/mineral-ui/mineral-ui/pull/478) that should help to speed up the build.

**Comment by brentertz** [comment]
After some research, I don't believe that this is something that we want to enable at this time for reasons mentioned above.  We can revisit this later if it truly becomes a bottle-neck.

**Comment by trotzig** [comment]
Cool, thanks for the update!
