### ISSUE TITLE
[Website] Optimize how site is crawled

### ISSUE THREAD

**Issue by riley** [mineral-ui/mineral-ui#484]
As a creator of Mineral UI, I would like lots of users to be able to find it. The easiest (and cheapest) way to do that is to optimize for search engines.

Google provides a Search Console for feedback on how mineral-ui.com is being crawled.

AC:

- [ ] create sitemap.xml
- [ ] figure out best way to update sitemap.xml in Search Console as our content updates
- [ ] add `hreflang` link element because Google wants to serve [language-specific links](https://moz.com/learn/seo/hreflang-tag) `<html lang>`
- [ ] add structured data to help google understand the site with [structured data](https://developers.google.com/search/docs/guides/intro-structured-data?visit_id=1-636463734628864902-406113399&hl=en&rd=1) and [rich snippets](http://schema.org/)
- [ ] tag page with Data Highlighting (some of our component names will show up in organic results)
- [ ] meta descriptions are unique per page
- [ ] AMP changes
- [ ] decide what (if any) pages we want hidden from indexing `robots.txt`

**Comment by coldpour** [comment]
broke out #495 and #494. the rest we don't think we need yet or ever.
