### ISSUE TITLE
[Table] Presentational components

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#516]
As a consumer of Mineral, I would like a tabular way to represent data, so that I can better align to mineral styling.

#### AC
1. Styled version of `<table> `
1. Support following styles
    - Zebra stripes
    - High contrast
    - Cell text wrapping (vertical-align top)
    - Header cell text wrapping (vertical-align bottom)
    - Content alignment (horizontal & vertical)
    - Hoverable rows
    - Row heights
    - Overflow scrolling

#### Other Considerations
- Supporting select/buttons (opinionated height vs natural height)
- Cell focus
- Variant rows/cells

**Comment by kylegach** [comment]
Hi, @karthikeayan. We just released our [first iteration of Table](https://mineral-ui.com/components/table), and will continue work on further features like column sorting and row selection with hopes of another release soon.

What kinds of features do you need?

**Comment by karthikeayan** [comment]
@kylegach Thats cool. I just want the simple table. Doc looks cool. Thank you!
