### ISSUE TITLE
update CONTRIBUTING

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#519]
make sure our contribution guide is accurate with our current process/philosophy/definition of done/etc.

Time to remove the "not accepting contributions" message?

**Comment by VictoriaVasys** [comment]
Additionally:
* Create a Mineral UI code sandbox user (and update pass-pack)
* Add a link for Mineral reproduction test case to README & issue template
* Ensure code of conduct is also up-to-date
