### ISSUE TITLE
[Dialog] component

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#527]
#### AC
Dialog (formerly called modal) should be built to help used complete discreet actions that would otherwise take them out of the normal flow of work.

MVP:
- Sections: header, contents, footer
- Un-opinionated content 
- Closing mechanisms
    * esc key - optional, consider event propagation 
    * X button - optional (mvp is just an X)
    * primary/secondary buttons (is there a public .close function)
    * click outside to close - optional prop
- Backdrop component
    * no scroll backdrop
- A11y
- Focus management
- Size props: S, M, L
- Tab indexing
- z-index (dialog itself, content inside)

#### Consider
- Modal  (no interaction with other controls)  vs. Modeless 
- Render props (investigate at a minimum)
- Animations (post-mvp)
- Widths vs Layout vs Content (multi-column)
- Scroll bars
- links in the footer (vs actions)
- best practices for footer actions (do these extend to popover?)
- Does this need to support "portals"
- Is always controlled? Does it have it's own state?
- Variants
  - Warning: Moving could have unintended consequenses
  - Danger: Deleting data will delete
  - Reset??
- Lazy children for use in table
- transition config
- portal

#### Design specs
source: https://preview.uxpin.com/871cc8a4f408b19ba0af468631cd762258212741#/pages/83832382/specification/sitemap

**Comment by brentertz** [comment]
Placing story on hold...

**Branch**
https://github.com/mineral-ui/mineral-ui/tree/527-dialog

**Demo**
http://527-dialog--mineral-ui.netlify.com/components/dialog

**Comment by VictoriaVasys** [comment]
## Future Work

- Animation prop to override default
  - Or theme variable(s)?
- Full-screen
  - Placement prop? Or overrides placement?
- Option to display close to top (v. vertically centered)
  - Placement prop
- DialogManager?
  - Children as render function
  - for stacking dialogs or for rendering multiple modeless dialogs as notifications?
- Could expose internal state or helper functions - eg. Close
  - Dialog children - could always expect be a function, that gets provided with helpers, e.g. close
- Is the “contextual” example approach sufficient/robust enough?
  - iframe
  - Button to open normally
  - Private contextual/static/inline prop on real Dialog?
    - To render inline and work for examples?
      - Basically just need to make it clear to users that the examples are different than normal - perhaps a callout will suffice
  - Here is how bootstrap modals document this stuff - https://getbootstrap.com/docs/4.0/components/modal/
    - Can this be accomplished via usePortal prop?
    - May be needed for nested dialogs
- keepMounted/lazy option? - perf/seo
- Placement prop would be useful for modeless mode
  - Definitely when implement notifications, etc
