### ISSUE TITLE
[Mineral UI Link - README.md] - https://mineral-ui.github.io/ returns 404

### ISSUE THREAD

**Issue by njsokol** [mineral-ui/mineral-ui#528]
### Expected behavior
I expected to see a website at the end of the url.

### Current behavior
I receive a 404 error.

### Steps to reproduce (for bugs)
1. Visit https://mineral-ui.github.io/

### Environment
Using Chrome

**Comment by brentertz** [comment]
Hi @njsokol.  Thanks for reporting the broken link.  I have updated it in the readme.  It now points to https://mineral-ui.com.
