### ISSUE TITLE
Typography headings are the wrong size

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#534]
The typography examples in tables in our Typography page are rendering much smaller than expected from the design. This is most likely due to using a table which we have yet to make a component for.

#### AC
1. All 10 examples in the typography page should follow the [Design Spec](https://ca.invisionapp.com/d/main#/console/11070131/250301092/preview)

#### Screenshots

![Screen Shot 2018-01-11 at 11.50.47 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552ea384a95d40fb005e28ea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f26b7191a379ee0c2e51415b49bc30254d58eeb9cb74fce36f34985619e8d86c5b25953e13ffb0d01cb806ba20884cd3b0bede1d95fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae44b5ca2143067e77e326e0a.png)

![Screen Shot 2018-01-11 at 11.51.05 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/552ea384a95d40fb005e28ea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f26b7191a379ee0c2e50415f4bbc30254d58eeb9cb74fce36f34985619e8d86c5b25953e13ffb0d01cb806ba20884cd3b0bede1d95fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae44b5ca2143067e576356e0a.png)

**Comment by kylegach** [comment]
@asagray — Just fixed this in PR #580. Take a look if you want. Ended up fixing font-weight in addition to font-size, and some of the table content was incorrect per spec.
