### ISSUE TITLE
Line height is creating half-pixels

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#535]
Our line height is creating half pixels which are rendering differently across browsers.

1.25 x 14 (root) = 17.5 line height. 

Normally, this isn't a problem. When the line-height is greater than the height of a component however, it will create unintended vertical distance between items.

See, radio / radio group for example.

Steps to resolve:
Design around reducing line-height or increasing the size of other smaller components.

**Comment by asagray** [comment]
We were looking at this, and I want to understand a little more about the line-height comment. Is this a special line-height for radio/check? Or are we running into the issue that we pointed out earlier where the line-heights on paragraph and other styles don't reflect what we spec'd?

On paragraph, we spec'd line-height to be 1.43, which is 20.02px. I believe this rounds down in all browsers.
