### ISSUE TITLE
Photoshop Templates

### ISSUE THREAD

**Issue by gfsmfk** [mineral-ui/mineral-ui#541]
As a UI designer I need a PSD template of all the components in this project so I can design the UI and so I can add to various sketching UX products before the developers get their hands on it and mess everything up.

**Comment by gfsmfk** [comment]
-The file type should be a PSD
-Each component should be contained in its own layer
-Each element of a component should be available and consistent with how a component might be modified on a code level 
-Each component should have its visual representation associated with its various states, opened, closed, on click, on-hover, etc.

**Comment by brentertz** [comment]
Hi @gfsmfk Thanks for submitting an issue.  It feels like this request would be better suited to the  [mineral-ui/design-assets](https://github.com/mineral-ui/design-assets) project.  Can you please re-open it there?

**Comment by brentertz** [comment]
cc @asagray

**Comment by asagray** [comment]
Hi @gfsmfk we have no plans to provide photoshop files at this time. We are going to be releasing a robust symbol library for Sketch App in the mineral-ui/design-assets project. I expect we'll have coverage of existing and a few future-thinking symbols by early to mid February.
