### ISSUE TITLE
[Dropdown] isOpen={null} causes errors in [PopoverTrigger]

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#549]
As a consumer, I want to be able to pass `null` to Dropdown's `isOpen` prop and not get errors from PopoverTrigger so that I can clearly understand what I've done wrong and make the necessary changes.

Currently, I'm confused why `PopoverTrigger` is involved since I'm interacting with `Dropdown`.

#### AC
1. passing `null` to `isOpen` should work the same as `undefined`

#### Consider
- many libraries using the controlled pattern use a "non-strict" comparison `!= null` to match `undefined` and `null`.

**Comment by brentertz** [comment]
@coldpour When reporting issues, please follow the issue template.  You have not provide enough context to make this issue easily actionable.  

The documentation states that the isOpen prop is a boolean.  In your example, you have provided a null value, which is not quite the same.  Does the Dropdown programmatically pass null to PopoverTrigger without the user having done anything or does this only occur when you have provided null to isOpen?

**Comment by coldpour** [comment]
@brentertz, I'm sorry, I submitted this issue through waffle.io which apparently doesn't make following issue templates obvious...

I understand that the documentation says "boolean" and that there are flow typings available, but if I'm not using flow, and I accidentally pass in a null (widely understood to be false-y in JS) instead of strict bool, then the resulting error isn't particularly helpful to pinpoint what I've done wrong.

**Comment by brentertz** [comment]
Sounds like a feature request for waffle...

**Comment by coldpour** [comment]
looks like this got fixed in v0.19.0!
