### ISSUE TITLE
[Tooltip] delay customization

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#550]
how opinionated should we be on our Tooltip's delay?

it's currently slated for being a hardcoded value. but do we want a choice of small, medium, large? or perhaps it would be better to allow any number under a certain maximum?

**Comment by brentertz** [comment]
@coldpour Who exactly are you posing this question to?  I doubt that our users care about this level of minutiae.  My recommendation is to hardcode the value for now.  The reasons for this recommendation follow.

1. If you choose a good value, it is doubtful that people will want/need to change it.
2. It keeps the API surface area smaller
3. If there is ever a demand for it, we can simply add a prop.  If we go this route, I wouldn't recommend to overthink the value either.  Just take any numeric value, but be sure to document what the units are e.g. seconds vs. milliseconds

**Comment by coldpour** [comment]
@brentertz I was asking our team. Several other libraries support an arbitrary delay prop. Since our team hadn't discussed it, I thought that might be worth doing. I think @kylegach and I came up with the same conclusion you did.
