### ISSUE TITLE
Font smoothing is not set to antialiased [Design]

### ISSUE THREAD

**Issue by asagray** [mineral-ui/mineral-ui#552]
### Expected behavior

On OS X, fonts weights, such as 600 semi-bold should render smoother and more akin to the design of the typeface than they appear currently. 

### Current behavior

 Font smoothing is not currently applied. 

### Possible solution

Recommend applying `-webkit-font-smooth: antialiased;` and `-moz-osx-font-smoothing: auto`

**Comment by coldpour** [comment]
@asagray, thanks for the submission! :sparkles:

We have a concern that applying antialiased fonts will incur a performance impact. We will assess that impact if any and make this fix if that turns out to be negligible.

Cheers!

**Comment by kylegach** [comment]
Per https://www.zachleat.com/web/font-smooth/ (particularly the conclusion), I don't believe it would be wise to apply this to all components.
