### ISSUE TITLE
[Button] Need to fix background color, font, icon

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#553]
**### Expected behavior**
1.1 Success 'Default' background color: green-60
1.2 Success 'Hover' background color: green-50

2.1 Warning 'Default' background color: bronze-60
2.2 Warning 'Hover' background color: bronze-50

3. 'Disable' font and icon color: gray-40

4. Sample icon 'cloud': please use [cloud.svg.zip](https://github.com/mineral-ui/mineral-ui/files/1686704/cloud.svg.zip)

**### Current behavior**
1.1 Success 'Default' background color: green-80
1.2 Success 'Hover' background color: green-70

2.1 Warning 'Default' background color: orange-60
2.2 Warning 'Hover' background color: green-50

3. 'Disable' font and icon color: gray-50

4. Sample icon 'cloud': has no custom gutter inside

**### Possible solution**
Needs to change the correct color values

**Comment by kylegach** [comment]
All color issues addressed in #596.

Only remaining issue is the cloud icon, which is only for illustrative purposes in the site and will thus not be changed.
