### ISSUE TITLE
[Dropdown] Some color values needs to change

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#557]
### Expected behavior
1. menuItem 'hover' background color: gray-10
2. menuItem 'active' background color: gray-20
3. Basic Usage section - Avatar: size should 24x24 

4.1 Success 'hover' background color: green-10
4.2 Success 'hover' background color: green-20

5.1 Warning 'hover' background color: bronze-10
5.2 Warning 'hover' background color: bronze-20

6.1 Danger 'hover' background color: red-10
6.2 Danger 'hover' background color: red-20

### Current behavior
1. menuItem 'hover' background color: gray-20
2. menuItem 'active' background color: gray-30
3. Basic Usage section - Avatar: size was 32x32

4.1 Success 'hover' background color: green-20
4.2 Success 'hover' background color: green-30

5.1 Warning 'hover' background color: orange-20
5.2 Warning 'hover' background color: orange-30

6.1 Danger 'hover' background color: red-20
6.2 Danger 'hover' background color: red-30

**Comment by kylegach** [comment]
All color issues addressed in #596.
