### ISSUE TITLE
[Radio Group] Minor values change

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#563]
### Expected behavior

Padding between Lable and Formfield: 8px padding
Caption: We recommend the location of the caption should below the Label (We can provide the optional variation which is located bottom the the field) see (https://ca.invisionapp.com/d/main#/console/11070131/250302831/preview)

### Current behavior

Padding between Lable and Formfield: 7px padding
Caption: located bottom of the field
### Possible solution
Needs to change the correct color values

**Comment by kylegach** [comment]
Duplicate of #556.
