### ISSUE TITLE
[TextArea] padding and color

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#564]
### Expected behavior

1. Available Sizes - small and medium padding left: 8px

2.1 Default 'default' border color: gray-40
2.2 Default 'focus' outline color: theme-70

3.1 Success 'default' border color: green-60
3.2 Success 'hover' border color: green-50
3.3 Success 'active' border color: gray-40
3.4 Success 'focus' border color: gray-40
3.4 Success 'focus' outline color: green-70

4.1 Warning 'default' border color: bronze-60
4.2 Warning 'hover' border color: bronze-50
4.3 Warning 'active' border color: gray-40
4.4 Warning 'focus' border color: gray-40
4.4 Warning 'focus' outline color: bronze-70

5.1 Warning 'default' border color: red-60
5.2 Warning 'hover' border color: red-50
5.3 Warning 'active' border color: gray-40
5.4 Warning 'focus' border color: gray-40
5.4 Warning 'focus' outline color: red-70

6. readonly text color: gray-60

### Current behavior

1. Available Sizes - small and medium padding left: 16px

2.1 Default 'default' border color: green-60
2.2 Default 'focus' outline color: none

3.1 Success 'default' border color: green-60
3.2 Success 'hover' border color: none
3.3 Success 'active' border color: gray-40
3.4 Success 'focus' border color: gray-40
3.4 Success 'focus' outline color: none

4.1 Warning 'default' border color: bronze-60
4.2 Warning 'hover' border color: none
4.3 Warning 'active' border color: gray-40
4.4 Warning 'focus' border color: gray-40
4.4 Warning 'focus' outline color: none

5.1 Warning 'default' border color: red-60
5.2 Warning 'hover' border color: none
5.3 Warning 'active' border color: gray-40
5.4 Warning 'focus' border color: gray-40
5.4 Warning 'focus' outline color: none

6. readonly text color: gray-80

**Comment by kylegach** [comment]
The sizes portion of this is fixed as part of #469.
