### ISSUE TITLE
[Icon Assets] Drop down arrow icon needs update

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#567]
Blocked: Need redline to assess implementation details.

### Expected behavior
Please update the assets using this SVG file.
[ dropdown.zip](https://github.com/mineral-ui/mineral-ui/files/1704230/dropdown.zip)

### Current behavior
The arrow on the small size of the button looks small, so we need to size up the button icon itself.

**Comment by Mikewaite** [comment]
Can you please include some specifications of what is wrong so we can make sure we can meet expectations. Some redlines of current behavior vs expected would be ideal.

**Comment by jeeyoung** [comment]
Our designer Sun is currently working on the icons.

**Comment by Mikewaite** [comment]
Closing for greater icon replacement issue.
