### ISSUE TITLE
[color] Color Palette Architecture

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#570]
As a developer, I would like consistency in color ramps so I do not have to do more work based on which color I pick. 

First identified in #553

**Blocked on design color work**

#### AC
Design:
Create color ramps that are consistent with contrast ratios. ie. 50 to 60 is always the same change of white to black text on color.

Dev:
Warning and Success button colors are not currently AA compliant, fix.
Update color names 
Update theme variable
Simplify theme logic
- Remove "color-text-on-primary"

Additional Effort on QA across all components for color usage. 

#### Other considerations:
Re-think structure of color theme variables (see #376)

**Comment by CAjeeyoung** [comment]
Please check the updated version of the color palette.
https://ca.invisionapp.com/d/main#/console/11070131/250301076/preview

**Comment by jeeyoung** [comment]
Please check the updated version of the color palette.
https://ca.invisionapp.com/d/main#/console/11070131/250301076/preview

**Comment by kylegach** [comment]
Follow-up identified:

- [ ]  Audit reality vs. readableColor vs. palette spec
- [ ]  TextInput & TextArea (others?) border colors
- [ ]  Other variant related gotchas?
