### ISSUE TITLE
[TextInput] control loses focus after typing 1 character

### ISSUE THREAD

**Issue by louvuono** [mineral-ui/mineral-ui#609]
Using a controlled or uncontrolled TextInput, when typing in the input box, after 1 character is typed the onChange handler is called and the input box loses focus.  Am unable to complete a full string unless I keep clicking in the box to enter the next character

**Comment by brentertz** [comment]
Hi @louvuono Thank you for the report.  This looks like a legit bug.  My guess is that it was likely introduced in v0.21.0.  We'll investigate...  In the mean time, you may want to give v0.20.0 a try.

**Comment by brentertz** [comment]
@louvuono This issue has been fixed and released in v0.22.0.
