### ISSUE TITLE
createTheme should allow user defined color palette

### ISSUE THREAD

**Issue by brentertz** [mineral-ui/mineral-ui#623]
As a user, I would like to provide my own color palette so that creating a custom theme is easier.

It is currently difficult for users to create a custom theme with different colors as you would need to override colors on every component.  Allowing custom color palettes would enable simpler global changes.

**AC:**

* Users can provide own color palette when defining a theme
* Users can provide semantic (danger, success, warning) color ramps
* Examples and documentation updated

**Other Considerations:**

* This will likely involve a breaking API change
* Might want to communicate the importance of color choices on accessibility
* This story should probably follow any other global color update stories that may be in progress.

**Comment by mnovinger** [comment]
if you want an example of a different color palette https://design.workday.com/guidelines/visual/colors

**Comment by kylegach** [comment]
@mnovinger — Just published a pre-release of this work, [v0.33.0-alpha.0](https://www.npmjs.com/package/mineral-ui/v/0.33.0-alpha.0), along with a preview of the [updated docs for `createTheme`](https://623-theme-from-palette-2--mineral-ui.netlify.com/theming#common-scenarios-theme-your-entire-app-create-your-own-theme-use-a-custom-color-palette).

We’ve decided that translating a palette with, say, 6 values per color to one with 10 values per color is an exercise best left to the consumer. Doing so programmatically would be (1) computationally expensive and (2) heavily opinionated in ways that likely contradict the needs of the particular consumer. That said, we’re happy to sit down with you sometime and help you figure out what that could like for Workday.

In the meantime, we’d love to hear your thoughts on the new `createTheme` API and its capabilities.
