### ISSUE TITLE
TextInput looses focus (controlled components)

### ISSUE THREAD

**Issue by alexg-dev** [mineral-ui/mineral-ui#637]
### Expected behavior
After keypress focus should remaining on `<input>` element

### Current behavior
After keypress `<input>` looses focus

### Possible solution
Add `key` property to each element

### Steps to reproduce (for bugs)

1. Create element `<TextInput value={...} onChange={...}>`
It's important to create controlled one with `value` and `onChange` provided

<details><summary>ControlledTextInput.js</summary><p>

```js
onChange (value) {
  setState({ value })
}

...

<TextInput
  key='text-input'
  value={this.state.value}
  onChange={e => this.onChange(e.target.value)}
/>
```
</p></details>

### Context
Controlled Text Input

### Version
0.21.0

**Comment by kylegach** [comment]
Thanks for the bug report, Alex. We've [addressed this in v0.22](https://github.com/mineral-ui/mineral-ui/issues/609).
