### ISSUE TITLE
[Select] doesn't react on selection change

### ISSUE THREAD

**Issue by alexg-dev** [mineral-ui/mineral-ui#645]
`[Select]` doesn't react on any change. After clicking on an option, it does nothing.
As a result, `onChange/onSelect` or even `onClick` provided for every single item are not called.

### Expected behavior

`[Select]` should change it's value and callbacks should be called.

### Current behavior

After clicking on an option, nothing happens. The state of `[Select]` remains the same.

### Steps to reproduce (for bugs)

Create `[Select]` with `data` property

<details><summary>Select.js</summary><p>

```js
renderSelect () {
    let v = [
      {text: 'a', value: 'a', onClick: () => console.log('click first')},
      {text: 'b', value: 'b', onClick: () => console.log('click second')}
    ];
    return (
      <Select data={v} />
    );
  }
```
</p></details>

### Context

Doesn't depend on context, have tried this on empty page.

### Version

0.22.0

**Comment by brentertz** [comment]
Hi @alexg-dev Thanks for filing an issue.

As far as I can tell, using mineral-ui@0.22.0, the Select component seems to call the `onSelect` and item `onClick` handlers as expected.  Please have a look at the following example.

https://codesandbox.io/s/6wlpo392qr

Looking a bit further, I did discover an issue with the `onChange` handler not being called as expected.  I will submit a fix for this shortly.

**Comment by brentertz** [comment]
@alexg-dev `mineral-ui@0.23.0` has been published, containing a fix for the `onChange` issue that I mentioned above.  If your handlers are still not being called, we'll have to investigate further.  Providing some environment details might be beneficial, e.g. browser/version, OS.

**Comment by brentertz** [comment]
@alexg-dev I am going to mark this as closed as everything appears to be working as expected.  If you continue to have difficulties, feel free to reopen it and provide some more details.  We would be happy to help.
