### ISSUE TITLE
[Website] Add duotone to site header

### ISSUE THREAD

**Issue by VictoriaVasys** [mineral-ui/mineral-ui#689]
Make site header more dynamic with a duotone effect: https://css-tricks.com/using-svg-to-create-a-duotone-image-effect/

**A/C**
* Use CSS duotone filter to implement two Mineral colors while keeping in accordance with Mineral tone (highlights close to white)
* State changes (& thus re-rendering) must be isolated; the rotation (or clicks) of mineral themes removes the filter

**Resources**
* Mike Holm's svg creation repo: https://github.com/coldpour/triangles (see index.js for quick adjustments of brightness, gem ball-size and application of duotone colors
* Mike Holm's blog post on creating the svg: https://codeburst.io/deleting-2000-lines-of-javascript-with-svg-424b89c6e466
* Mineral's site design guidelines
* Mineral UI branch with duotone implemented: https://github.com/mineral-ui/mineral-ui/tree/689-duotone-orange-0.5 (in order to prototype, change the whole svg file that is produced from Holm's repo)
* Victoria's initial prototypes: 
https://5af4757811b73b1974cf382c--mineral-ui.netlify.com/ (orangePunch-slate with 50% radius)
https://5af474d88df89463fbc371dc--mineral-ui.netlify.com/ (orangePunch-slate with 70% radius)
https://5af47455dd6a540cc66f37e0--mineral-ui.netlify.com/ (orangePunch-slate with 100% radius)
https://5af388a68df89476a7c371c4--mineral-ui.netlify.com/ (iconYellow-slate with 50% radius)
https://5af47345b13fb116f0ee4892--mineral-ui.netlify.com/ (iconYellow-slate with 70% radius)
https://5af473b00733d5430f76cf19--mineral-ui.netlify.com/ (iconYellow-slate with 100% radius)

**Comment by Mikewaite** [comment]
This is great, thank you.
