### ISSUE TITLE
[table] Table Component

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#690]
Tables are used to display all information from a data set.  Data can be compared and filtered to help make decisions.

Epic Links:
parent of #516  MVP
parent of #730  React component cell children bug
parent of #733  Striped hovered row bug
parent of #734  Sortable/selectable
parent of #735  Render props
parent of #741  Sortable column header design

**Comment by kylegach** [comment]
https://www.google.com/search?hl=en&q=aria%20interactive%20grid
