### ISSUE TITLE
v1 issues to complete

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#698]
As we approach a stable v1, we need to complete the following issues.

component work
Alerts / Notifications
Divider
List
Pagination
Tabs

extending existing components
Multi-Select
Button Group
*spacing variables

Non-component work
base theme review
React version strategy, update APIs
Polyfill Strategy
Replacement for Glamorous breaking changes
RtL breaking changes (Mineral provider)
Naming consistency breaking changes
final accessibility test 
check for consistency on naming props
website consistency pass
check popper visual diffs

**Comment by kylegach** [comment]
Addition:

Is the "px on the root, ems inside" approach the right one? It doesn't respect the browser's default font-size, and adds significant complexity to our code. I'm not convinced it's worth the primary reason of consumers not having to worry about their document's root font-size.
