### ISSUE TITLE
Remove "regular" variants

### ISSUE THREAD

**Issue by brentertz** [mineral-ui/mineral-ui#707]
Some components have the notion of a "regular" variant.  There should be no such thing and this should be considered an anti-pattern.  In such a case, it should simply be the default implementation.

**Comment by Mikewaite** [comment]
Would the default of something that is a variant negate this?

For instance, a default success pattern.

**Comment by brentertz** [comment]
No, you would just set default value of the variant prop to be success.  I am just suggesting that we don't set a default value of variant, rather than set it to "regular".
