### ISSUE TITLE
[StartEnd] doesn't go to start in IE11

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#710]
### Expected behavior

![screen shot 2018-06-07 at 9 59 00 am](https://user-images.githubusercontent.com/10870252/41112081-324be800-6a3b-11e8-8596-56306bcdd34b.png)

### Current behavior

![screen shot 2018-06-07 at 9 58 40 am](https://user-images.githubusercontent.com/10870252/41112094-391b63cc-6a3b-11e8-90eb-46d4a8cfc41c.png)

### Possible solution

not sure

### Steps to reproduce (for bugs)

1. open IE11
2. go to http://mineral-ui.com/components/start-end/basic

<details><summary>YourFileName.js</summary><p>

```js
// Please paste your code here
```
</p></details>

### Version

0.33

### Environment

prod

**Comment by kylegach** [comment]
This turned out to be an issue with the demo-only styles we use for illustration purposes on the site. The component itself functions correctly.
