### ISSUE TITLE
[FlexItem] shrinks too much in IE11

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#713]
### Expected behavior

![screen shot 2018-06-07 at 12 22 47 pm](https://user-images.githubusercontent.com/10870252/41118642-c12460c2-6a4d-11e8-822a-4c40a6eb2a65.png)

### Current behavior

![screen shot 2018-06-07 at 12 23 21 pm](https://user-images.githubusercontent.com/10870252/41118630-bc10f4f6-6a4d-11e8-816c-7cdca049c5f5.png)

### Possible solution

not sure

### Steps to reproduce (for bugs)

1. open IE11
2. go to http://mineral-ui.com/components/flex-item/shrink

### Version

0.33

### Environment

prod

**Comment by kylegach** [comment]
Made a simplified test case, http://jsbin.com/napenakuje/1/edit?html,css,output, proving that this is an IE11 bug and not an issue with our code. It's not listed here: https://github.com/philipwalton/flexbugs, and I can't find a workaround.

However, it seems related to the relatively drastic ratio between the shrink values of 1, 2, and 3 (change the `flex-shrink` of `.one` to something less than 2.5 and it displays fine; change the shrink of `.two` to 3, and it also displays fine). Such a scenario is probably unlikely in actual application of the component.

Thinking our possible future actions are: 1) close the issue, 2) polish up that simplified test case and submit to flexbugs, and/or 3) pour more hours into trying to find a fix on our end.

**Comment by Mikewaite** [comment]
I'm okay with closing this.

**Comment by kylegach** [comment]
Closing for reasons discussed above.
