### ISSUE TITLE
Consistent look and feel in forms

### ISSUE THREAD

**Issue by nuplo** [mineral-ui/mineral-ui#720]
Hi,
I would like to migrate on mineral-ui forms. I think FormField doesn't support all form elements. Is it possible to have consistent layout (labels, error messages, require, etc.) on all elements? I would like to keep consistent look and feel in 1 form with elements like: text input, text area, select box, radio buttons, check boxes and file upload. 

Thanks,
Adam

**Comment by Mikewaite** [comment]
Hi Adam,
Do you have an example of how the mineral text input, text area, select box, radio and buttons don't have consistent layout?

Besides file upload, are there other form elements you are missing in Mineral?

Thanks,
Mike

**Comment by kylegach** [comment]
Adam,

As Mike pointed out, we have Mineral components for all of those except file upload. In addition to those Mineral components, FormField supports _any_ input component that renders an HTML form control.

Example: https://codesandbox.io/s/mmzn0y4jyj
Docs: http://mineral-ui.com/components/form-field#basic

Please let us know if you are still missing some necessary functionality. Thanks!

**Comment by nuplo** [comment]
Ok, `createStyledComponent` that's what I was looking for! Thanks for this example.
