### ISSUE TITLE
[Table] component fails with error when cell content is a React element.

### ISSUE THREAD

**Issue by limscoder** [mineral-ui/mineral-ui#730]
### Expected behavior

Cell can contain React element.

### Current behavior

`deepEqual` comparison in `DataRow.shouldComponentUpdate` fails when cell content is a React element.

![screen shot 2018-07-12 at 9 30 17 am](https://user-images.githubusercontent.com/121623/42647487-64922e54-85c1-11e8-90ad-68d07daea84d.png)

### Possible solution

Change `shouldComponentUpdate` behavior.

### Steps to reproduce (for bugs)

1. Render table with React component in cells.
2. Re-render parent component.

### Version

0.37.0, fast-deep-equals v2.0.1

**Comment by brentertz** [comment]
@limscoder I am having difficulty reproducing this locally in jest/enzyme or in CodeSandbox.  Can you please try to reproduce the issue in the following CodePen?

https://codesandbox.io/s/x9k1p8lm1p

**Comment by brentertz** [comment]
If we can reproduce the issue, we can look into replacing https://github.com/epoberezkin/fast-deep-equal with https://github.com/FormidableLabs/react-fast-compare

**Comment by brentertz** [comment]
Still unable to reproduce issue, but I published a test version `mineral-ui@dunit` and @dunit confirmed that it solved his issue.  See https://github.com/mineral-ui/mineral-ui/compare/730-table
