### ISSUE TITLE
[Table] Row onClick

### ISSUE THREAD

**Issue by G0L0L** [mineral-ui/mineral-ui#736]
As a consumer of Table component, I would like to be able to handle click event on single Table row.

**Comment by brentertz** [comment]
Hi @GOLOL,

Thanks for your feature request.  Whilst Table doesn’t currently support custom props to be set directly on a row, we do have a [story](https://github.com/mineral-ui/mineral-ui/issues/735) on deck that should help to accomplish this task as well as offer much greater individual component customization capabilities.  

In the mean time, you may be able to accomplish your objective by adding an `onClick` handler to the table and then using javascript to filter the events that you are interested in.  e.g.  https://codesandbox.io/s/jpprnjlw19

**Comment by brentertz** [comment]
Table render props were added in https://github.com/mineral-ui/mineral-ui/pull/776.  See https://mineral-ui.com/components/table#custom-row for an example.
