### ISSUE TITLE
[CardFooter] Expand toggle interaction styles don't respect Footer variant

### ISSUE THREAD

**Issue by ender2012** [mineral-ui/mineral-ui#740]
### Expected behavior
The expand more/less toggle on the card footer should have hover/user interaction styles that reflect the variant used on the footer.

### Current behavior
Regardless of variant, the toggle icon hover color is still set for the default footer styles.

### Steps to reproduce (for bugs)

```js
<CardFooter
            variant="success"
            expandable
            isOpen={this.state.isOpen}
            onOpen={this.onOpen}
            onClose={this.onClose}
            title="Footer Title">
```
</p></details>

### Context
Hovering and interacting with the expand toggle within a variant footer is visually jarring.

### Version
0.37

### Environment
churroland

**Comment by kylegach** [comment]
Thanks for the detailed report, @ender2012.

I just submitted a PR to address the issue, which you can preview like so:

1. Open https://740-card-footer-variant--mineral-ui.netlify.com/components/card-footer/variants
2. Add the `expandable` prop to one or more of the CardFooters rendered in that example
3. Confirm that the hover styles match the variant now

The change should be released in the next couple days.

FYI, I used the [`backgroundColor_<variant>_hover`](https://mineral-ui.com/theming#background) theme variables for the colors.
