### ISSUE TITLE
[Button] Padding in pixels destroys the component

### ISSUE THREAD

**Issue by G0L0L** [mineral-ui/mineral-ui#747]
```
const DownloadButton = createThemedComponent(Button, ({ theme }) => ({
  Button_paddingHorizontal: theme.space_inset_lg,
}));
```

works perfectly, but 

```
const DownloadButton = createThemedComponent(Button, ({ theme }) => ({
  Button_paddingHorizontal: '30px',
}));
```
gives next results

![image](https://user-images.githubusercontent.com/1982853/43212674-e87261e4-9034-11e8-9602-7fb83316fe7a.png)

![image](https://user-images.githubusercontent.com/1982853/43212774-3443d3e6-9035-11e8-9078-5fbf794e739f.png)

**Comment by brentertz** [comment]
@G0L0L Admittedly, it is not clearly documented, but theme variable overrides should maintain the original units.   In this case, `space_inset_sm` as used by `Button_paddingHorizontal` is in ems, as shown [here](http://mineral-ui.com/theming#space).  If you wish to specify the units in pixels, you can use the `pxToEm` util.

```js
import Button from 'mineral-ui/Button';
import { createThemedComponent } from 'mineral-ui/themes';
import { pxToEm } from 'mineral-ui/styles';

const ThemedButton = createThemedComponent(Button, {
  Button_paddingHorizontal: pxToEm(30)
});

```

**Comment by G0L0L** [comment]
Thanks for explanation! But it would be really nice to document this.
