### ISSUE TITLE
[Table] New property request

### ISSUE THREAD

**Issue by G0L0L** [mineral-ui/mineral-ui#752]
As a consumer of Table components, I would like to define `rowsLimit` property, which will limit maximum number of rows to render (even if data has more entries).

The scenario:
I have data consists of 100 rows, but I don't want to render them at once. Instead of this I'm going to render it in chunks. Each chunk has 20 rows. So from begging I'm passing to the component data array consisted of 20 rows, by clicking on "Show more" button next 20 rows are added to data and so on.

The problem:
If I have set sorting, it obviously sorts only the data array I passed to component. And when new rows are added, they can appear on any place (since my original data is not sorted).

The solution:
With `rowsLimit` property I no longer need to make data chunks, instead of this I'm passing all my data with a limit. So the component can sort all data and render exact number of sorted rows.

**Comment by kylegach** [comment]
Nice timing. 🙂

We just submitted a PR to add a Pagination component, which adds a new Table example illustrating how to paginate a sorted table: https://147-pagination--mineral-ui.netlify.com/components/table/sortable-paginated (that's a preview link, because the PR hasn't been merged yet).

While you're not technically paginating your data, I think the same priniciples (do the sorting on the full data set and then pass Table a sliced subset of that data) will apply.

I'm going to close this issue for now, as I believe that example shows that a new prop isn't necessary, but feel free to re-open if I misunderstood or your disagree.

**Comment by kylegach** [comment]
Thank you for the clear, contextual explanation of your request, by the way. 👍

**Comment by G0L0L** [comment]
Hi @kylegach , thanks for the response. If I understand the PR correctly, using `Table.defaultSortComparator(a,b,sort.key))` in my code won't use `sortComparator`s I passed in columns definition. Take a look [here](https://github.com/mineral-ui/mineral-ui/blob/dea67a948d3c980cdf541f9b21c92c08e6cd9364/src/library/Table/Sortable.js#L98).

**Comment by G0L0L** [comment]
Also, imho sorting should not be performed in case of controlled `SortableTable`, since data are already sorted.

The scenario:
I would like to render html in some table cells, so instead of just passing raw data, I'm passing React.Elements.
```
render () {
  const data = this.props.data
    .slice(0)
    .sort(...someParams)
    .map(item =>({
      rawValue1: item.rawValue1,
      rawValue2: this.renderValue2(item.rawValue2)
    }));

   return (
     <Table data={data} />
    );;
}
```

The problem:
In this case additional sorting [here](https://github.com/mineral-ui/mineral-ui/blob/9105116051379a60657657f3e7b3521318b7345c/src/library/Table/Sortable.js#L100) is trying to compare React.Elements instead of raw data and actually destroying proper order.

**Comment by kylegach** [comment]
Alex,

After discussing, I think you raise valid points in both of your comments here. Re-opening with a PR incoming...

**Comment by kylegach** [comment]
@G0L0L,

PR: https://github.com/mineral-ui/mineral-ui/pull/759

Relevant sample code: https://752-sortable-improvements--mineral-ui.netlify.com/components/table/sortable-paginated

Please let us know if you anticipate this PR solving your problem. We can also make a pre-release for you, if you'd like to test it in your app.

Finally, we have an issue, https://github.com/mineral-ui/mineral-ui/issues/735, for providing a render prop for each cell in a column, which we plan to start on soon. While the issues raised here are valid, I believe that would be the more appropriate way to render complex content in the future.

Thank you for bringing these shortcomings to our attention.

**Comment by G0L0L** [comment]
@kylegach , thanks, looks great!

The only problem I can see is `this.state.data`. Here is your example

```
() => {
  class PaginatedTable extends Component {
    constructor(props) {
      super(props);

      this.state = {
        data: this.props.data,
        currentPage: 1,
        sort: undefined
      };

      this.handleSort = this.handleSort.bind(this);
      this.handlePageChange = this.handlePageChange.bind(this);
    }

    handleSort(sort, sortComparator) {
      const sortedData = this.state.data.slice(0).sort((a,b) => {
        const asc = sortComparator(a,b,sort.key);
        const desc = asc * -1;
        return sort.descending ? desc : asc;
      });
      this.setState(
        { data: sortedData, sort },
        () => { this.handlePageChange(1) }
      );
    }

    handlePageChange(currentPage) {
      this.setState({ currentPage })
    }

    render () {
      const { currentPage, data } = this.state;
      const pageSize = 3;
      const firstRow = (currentPage - 1) * pageSize;
      const lastRow = (currentPage - 1) * pageSize + pageSize;
      const slicedData = data.slice(firstRow, lastRow);

      return (
        <DemoLayout>
          <Table
            sortable
            sort={this.state.sort}
            onSort={this.handleSort}
            data={slicedData}
            columns={columns}
            title="Minerals"
            hideTitle
            rowKey="Name" />
          <Pagination
            currentPage={this.state.currentPage}
            onPageChange={this.handlePageChange}
            pageSize={pageSize}
            totalCount={data.length} />
        </DemoLayout>
      )
    }
  }

  return <PaginatedTable data={data}/>
}
```

The problem will occur when `PaginatedTable` component will be updated with new `data`. It simply won't be displayed since we copied `data` to `state` only in `constructor`. For sure, we can implement `getDerivedStateFromProps`, but in this case we should also store `sortComparator` function into `state` to be able immediately sort it.

Imho it's not really good solution, because
1. To be able to sort `data` I'm forced to copy it from `props` to `state`
2. I'm forced to have one more `state` entry `sortComparator`

Instead of this, in controlled `SortableTable` I would suggest to prohibit user to define `sortComparator` in column definition and let him  handle sorting completely by his own. Consider next example:

```
import memoizeOne from 'memoize-one';

() => {
  class PaginatedTable extends Component {
    constructor(props) {
      super(props);

      this.state = {
        currentPage: 1,
        sort: undefined
      };

      this.handleSort = this.handleSort.bind(this);
      this.handlePageChange = this.handlePageChange.bind(this);
    }

    handleSort(sort, sortComparator) {
      this.setState(
        { sort },
        () => { this.handlePageChange(1) }
      );
    }

    handlePageChange(currentPage) {
      this.setState({ currentPage })
    }

    sort = memoizeOne((data, sort) =>
      // ... here my custom sorting occurs
    );

    render () {
      const { currentPage, sort } = this.state;
      const pageSize = 3;
      const firstRow = (currentPage - 1) * pageSize;
      const lastRow = (currentPage - 1) * pageSize + pageSize;
      const slicedData = this.sort(this.props.data, sort).slice(firstRow, lastRow);

      return (
        <DemoLayout>
          <Table
            sortable
            sort={this.state.sort}
            onSort={this.handleSort}
            data={slicedData}
            columns={columns}
            title="Minerals"
            hideTitle
            rowKey="Name" />
          <Pagination
            currentPage={this.state.currentPage}
            onPageChange={this.handlePageChange}
            pageSize={pageSize}
            totalCount={data.length} />
        </DemoLayout>
      )
    }
  }

  return <PaginatedTable data={data}/>
}
```

P.S. I've got the inspiration from [this article](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization)

**Comment by kylegach** [comment]
Thank you so much for the help in shaping this, @G0L0L. I've updated the PR to take your latest comments into account.
