### ISSUE TITLE
[Color] Create new Base color +  Color Grades.

### ISSUE THREAD

**Issue by LeBonbom** [mineral-ui/mineral-ui#767]
Dear Mineral TEAM,

My Name is Diethelm and i work as an UX/UI Designer. I found your interesting project and wanted to raise an issue. I was very interested by your article https://uxplanet.org/designing-systematic-colors-b5d2605b15c It was adressing every discussable information that I was searching for in case of my color research.

We found the topic to be very interesting and of great value in finding color themes that work as dark and light version.
It would be a great thing to havethe initial color selection step. Which is quite dusty explained in the article. Like a small tool that lets you create and the color curve to start with one Base color and generate the rest. Or of course which lets you also edit the other colors and theirs distance in the color space. e.g. by adjusting the curve. 

Is there such a tool in use or was this all hard manual work? Maybe you have a hint for me

I think this would be one of the biggest USPs of your mineral theme. To live edit the base color and its gradients to see the results in an example light and dark interface. With the corresponding greyscale.

hope to hear from you

Diethelm

**Comment by kylegach** [comment]
Hi, Diethelm. Unfortunately, Mineral's color ramps were all "hard manual work", based on a lot of math and a skilled designer's eye for what works. We have discussed making a tool to automate the process, but it hasn't gone farther that just those discussions.

@jeeyoung was the designer primarily responsible for our color palette (and the author of the post you referenced), maybe he has some more insight he could share?

The good news is that once you have a custom color ramp defined, you can use [`createTheme`](https://mineral-ui.com/theming#common-scenarios-theme-your-entire-app-create-your-own-theme-use-a-custom-color-palette) to apply that ramp to your theme in the same manner as a standard color ramp.

I'm going to close this issue, but feel free to continue discussing here and we'll re-open if necessary.

**Comment by evilaliv3** [comment]
@kylegach @jeeyoung: I wonder if there has been any update on this and there is any tool that you would recommend to design the ramps?

I see in fact that you published a well detailed guideline:
https://uxplanet.org/designing-systematic-colors-b5d2605b15c

Thank you for your attention.

P.s. which is the tool used in the image below? Is it publicly avilable?
![image](https://user-images.githubusercontent.com/217034/95338575-5bf6c800-08b3-11eb-8e58-b97b8f1c94ae.png)

**Comment by kylegach** [comment]
Hi Giovanni,

Neither Jeeyoung nor myself are actively maintaining this project anymore, though he may still have some insights to share (I merely implemented his hard work into the theme).

FYI, @tx-nestor is the new point-of-contact for mineral-ui.

**Comment by evilaliv3** [comment]
Thank you @kylegach !

**Comment by evilaliv3** [comment]
@amiller-gh: i see that you have been able to apply these rules to Node.js in: https://medium.com/@ammiller/redesigning-nodejs-org-584212bb25e1

would you please clarify about the tools you used to replicate the methodology and create the ramp for for the green color of Node?
Do you recognize the tool in the screenshot above?
