### ISSUE TITLE
[Dialog] component renders nothing

### ISSUE THREAD

**Issue by G0L0L** [mineral-ui/mineral-ui#774]
Please take a look at this sandbox:
https://codesandbox.io/s/0m88397kql

Use `Dialog` as it is described on component page:
```
const App = () => (
  <Flex
    alignItems="center"
    height="100vh"
    justifyContent="center"
    padding="lg">
    <Dialog title="Dialog title" actions={[
      { text: 'Cancel' },
      { text: 'Action' }
    ]}>
      <Text>Dialog content</Text>
    </Dialog>
  </Flex>
)

render(
  <ThemeProvider>
    <App />
  </ThemeProvider>,
  document.getElementById("root")
);
```

**Comment by brentertz** [comment]
Hi @G0L0L , I believe that you are simply missing the `isOpen` prop.  

 It is up to the application to manage the open state of the dialog.  See the [trigger example](https://mineral-ui.com/components/dialog/trigger). 

Most of the examples on the dialog page are [modified](https://github.com/mineral-ui/mineral-ui/blob/master/src/website/app/demos/Dialog/components/DemoDialog.js) to render inline for illustration purposes.  There is a note to explain this at the top of the page, but perhaps it could be improved. Open to suggestions...

I am going to close this issue, but feel free to continue the conversation.

**Comment by G0L0L** [comment]
@brentertz, thanks for explanation
