### ISSUE TITLE
[Flow] Custom Types

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#78]
As a consumer using Flow, I want to understandable Flow types in Mineral. I would like to not have to define custom types.

AC:
* MnrlReactNode and other custom flow types should show up as standard react flow types
* Consumers do not get flow errors for our custom types.

Other Considerations:
* Button icon props use react $element should they use Mineral types
* check in with Brent before pulling.
* We may want to publish our types to flow-typed
* Likely to remove custom types and duplicate/replace definitions

**Comment by brentertz** [comment]
This issue with consumers getting Flow errors with mineral has been resolved previously by simply not publishing our flow-types.  This however is only a short term solution as some consumers will eventually like to have a typed library.  

#384 removes custom mineral flow types that would have caused the previous flow errors.

Another story will be created to publish mineral flow-types.
