### ISSUE TITLE
Update Milestones

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#79]
As a contributor, I want to know what milestone i'm working toward

AC:
1. Github Milestones and Roadmap.md file reflect reality
2. existing issues are tied to a milestone if applicable

Other Considerations:
Revisit the "goals" titles (lol increments)

**Comment by kylegach** [comment]
The [roadmap](https://github.com/mineral-ui/mineral-ui/blob/master/ROADMAP.md) and [milestones](https://github.com/mineral-ui/mineral-ui/milestones) have been updated.

Additionally ([almost](https://github.com/mineral-ui/mineral-ui/issues?utf8=%E2%9C%93&q=is%3Aissue%20no%3Amilestone)) all issues now have an associated milestone.
