### ISSUE TITLE
[Button] Doesn't trigger onSubmit in forms

### ISSUE THREAD

**Issue by xvalentino** [mineral-ui/mineral-ui#806]
### Expected behavior
A Mineral/Button's parent form's onSubmit method should be called when clicked.

### Current behavior
onSubmit is not triggered.

### Possible solution
find where `event.preventDefault()` is called and delete that line.
Or something else 🤷‍♂️ 

### Steps to reproduce (for bugs)

1.
2.
3.

```js
<form onSubmit={() => console.log('yay')}>
  <Button />
</form>
```

### Context

:(

**Comment by brentertz** [comment]
Mineral buttons have a default `type="button"`.  Can you please try changing the type to "submit"?

```js
<Button type="submit" />
```

**Comment by xvalentino** [comment]
Ah that makes sense, I'll give that a shot!
Thank you very much!

**Comment by xvalentino** [comment]
That worked, thanks!
