### ISSUE TITLE
[Menu][Link] Usage with React Router

### ISSUE THREAD

**Issue by sikula** [mineral-ui/mineral-ui#809]
### Context

I want to use the Menu component with React-Router's Link component (really the Mineral-Ui Link component), but so far I'm struggling to do that.  The Menu component doesn't seem to have an "href" prop like some of the other components, and if I wrap an Item around a Link, then my preferred styling is off.

Essentially, I'm trying to make it so when you click on a MenuItem, you get redirected to a different page.

```
import { ReactRouterLink } from 'react-router-dom'
import Link from 'mineral-ui/Link'
import { createThemedComponent } from 'mineral-ui/themes'
import Menu, { MenuItem } from 'mineral-ui/Menu'

const CustomItem = createThemedComponent(MenuItem, {
  MenuItem_color: '#fff',
  MenuItem_backgroundColor_hover: 'rgba(229, 229, 229, 0.05)',
  MenuItem_backgroundColor_focus: 'rgba(229, 229, 229, 0.05)',
  MenuItem_backgroundColor_active: 'rgba(229, 229, 229, 0.05)',
  MenuItem_backgroundColor_selected: 'rgba(229, 229, 229, 0.05)',
  MenuItem_paddingVertical: '0.2em',
  MenuItem_paddingHorizontal: '1em',
  MenuItemIcon_color: '#fff',
  MenuItem_fontWeight: '600',
  MenuItemContent_fontSize: '0.938em',
})


const menuItems = [
  {
    text: <div style={{ fontWeight: 600, fontSize: '1.250em' }}>Header</div>,
    secondaryText: <IconMoreHoriz size="large" />,
  },
  {
    text: <Link element={ReactRouterLink} to="/item1">Item1</Link>, // this doesn't work
    href: '/item1', // this doesn't work either
  },
  {
    text: 'ITEM 1',
  },
  {
    text: 'ITEM 2',
  },
]

const item = ({ props }) => <CustomItem {...props} />
const CompanyNav = () => (
  <div style={{ borderBottom: '1px solid rgba(216, 216, 216, 0.1)', paddingBottom: 10 }}>
    <Menu data={menuItems} item={item} itemKey="text" />
  </div>
)
```

I may have missed something, but overall I'm a little bit lost. Help would be appreciated.

**Comment by BarryThePenguin** [comment]
I had a play around with your example, there were a few mistakes?
This is what I ended up with..

```js
import React from "react";
import { Link as ReactRouterLink } from "react-router-dom";
import Link from "mineral-ui/Link";
import { createThemedComponent } from "mineral-ui/themes";
import Menu, { MenuItem } from "mineral-ui/Menu";
import IconMoreHoriz from "mineral-ui-icons/IconMoreHoriz";

const CustomItem = createThemedComponent(MenuItem, {
  MenuItem_color: "#fff",
  MenuItem_backgroundColor_hover: "rgba(229, 229, 229, 0.05)",
  MenuItem_backgroundColor_focus: "rgba(229, 229, 229, 0.05)",
  MenuItem_backgroundColor_active: "rgba(229, 229, 229, 0.05)",
  MenuItem_backgroundColor_selected: "rgba(229, 229, 229, 0.05)",
  MenuItem_paddingVertical: "0.2em",
  MenuItem_paddingHorizontal: "1em",
  MenuItemIcon_color: "#fff",
  MenuItem_fontWeight: "600",
  MenuItemContent_fontSize: "0.938em"
});

const menuItems = [
  {
    text: "Header",
    secondaryText: <IconMoreHoriz size="large" />
  },
  {
    text: "Item1",
    to: "/item1"
  },
  {
    text: "ITEM 1"
  },
  {
    text: "ITEM 2"
  }
];

const item = ({ props }) => {
  if (props.item.to) {
    return (
      <Link element={ReactRouterLink} to={props.item.to}>
        <CustomItem {...props} />
      </Link>
    );
  }
  return <CustomItem {...props} />;
}

const CompanyNav = () => (
  <div
    style={{
      background: "green",
      borderBottom: "1px solid rgba(216, 216, 216, 0.1)",
      paddingBottom: 10
    }}
  >
    <Menu data={menuItems} item={item} itemKey="text" />
  </div>
);
```

[I created this in codesandbox](https://codesandbox.io/s/rr95q05y8q)

**Comment by kylegach** [comment]
Thanks for chiming in, @BarryThePenguin! A few thoughts for you and @sikula:

- Your updated sandbox is mostly correct, Jonathan, but it does have some minor, easily addressed accessibility issues around focus styles and management. I created an annotated sandbox with details: https://codesandbox.io/s/o43v0k9rk5

- As an alternative, React Router exposes a [`history`](https://reacttraining.com/react-router/web/api/history) object which allows you to navigate imperatively. That allows something like this, which avoids Link entirely: https://codesandbox.io/s/xom3pp658q.

Navigation should use anchor (`a`) elements, so I'd probably use the first method despite its extra complications.

Also, users expect all items in a menu to behave the same, either all actions or all navigation. So even though the implementation of `item` allows for a mix (a good safeguard!), please consider maintaining consistency throughout your menu.

I'm going to close this for now, but feel free to comment if anything is unresolved.
