### ISSUE TITLE
[Navigation] Provide sub menu item

### ISSUE THREAD

**Issue by hedikasmanto** [mineral-ui/mineral-ui#818]
### Expected behavior
I would like if mineral UI provide navigation with sub menu item for topbar (horizontal) and sidebar  (vertical)

### Current behavior
Currently, Mineral UI just provide dropdown menu on topbar navigation (horizontal) for overflow only. 
No support for vertical / sidebar navigation 

### Possible solution
Dropdown Menu is so good. I think we can re-style Dropdown and DropdownContent as Accordion for vertical navigation.

### Version
Latest

**Comment by kylegach** [comment]
Hi Hedi,

Thanks for your suggestion.

Please see #815 for a conversation about sidebar navigation. We will likely begin working on this in the next few weeks.

For dropdown menus in a horizontal navigation, you should be able to build your own with PrimaryNav (or SecondaryNav) and Dropdown. If you submit an [RFC](https://github.com/mineral-ui/mineral-ui/tree/master/docs/rfcs) for that functionality (which may or may not be a new component), we'll consider including it in the library. However, we don't have much availability right now, so you (and/or other contributors) would likely need to do the bulk of the work.

I'm going to close this for now, as an RFC is the clear next step. Thanks!
