### ISSUE TITLE
[Grid] naming of component is confusing

### ISSUE THREAD

**Issue by pixelpony** [mineral-ui/mineral-ui#822]
### Expected behavior
The Flex component uses css flex layout. I expected the Grid component to use css3 grid layout.

### Current behavior
The parallel naming of Flex and Grid strongly implies the use of css grid layout for Grid component. It's perfectly acceptable to implement a grid using flex layout, but the current name is somewhat misleading, and also might make it harder to add a true grid layout component later without having to first dig yourself out of a naming hole. 

### Possible solution
Rename the component to FlexGrid?

**Comment by kylegach** [comment]
Hi, @pixelpony.

That's a fair point. I don't think it's worth a breaking change right now, but if we ever do create a CSS Grid Layout component ([which may not be wise, btw](https://www.rachelandrew.co.uk/archives/2017/07/01/you-do-not-need-a-css-grid-based-grid-system/)), we'd consider the change then. Fwiw, Grid (and GridItem) were chosen for their brevity and descriptiveness of purpose.
