### ISSUE TITLE
[SSR] give an example with next.js

### ISSUE THREAD

**Issue by avetisk** [mineral-ui/mineral-ui#823]
### Context
Would be awesome to add an example in the docs.

### Version
0.56

### Environment
next.js

**Comment by kylegach** [comment]
We agree! We won't have time to get to this for a while... but we'd be happy to look at a PR.

This could be helpful start: https://github.com/emotion-js/emotion/issues/1178#issuecomment-469098353

**Comment by brentertz** [comment]
Related: https://github.com/mineral-ui/mineral-ui/issues/824#issuecomment-477295390

**Comment by avetisk** [comment]
As of emotion 10, there is nothing particular to do. It works out of the box.
