### ISSUE TITLE
UXPin library?

### ISSUE THREAD

**Issue by acgray** [mineral-ui/mineral-ui#831]
UXPin is listed on http://adele.uxpin.com/ as having a UXPin library available but I can find no such library available for download anywhere.  Is that information now outdated?

Sorry if I'm missing something very obvious here but I suspect others will have the same question!

**Comment by scott-joe** [comment]
https://mineral-ui.com/getting-started

**Comment by kylegach** [comment]
@acgray — Yikes. We really dropped the ball on this, sorry.

Here is a [preview of the UXPin library used to build Mineral](https://preview.uxpin.com/871cc8a4f408b19ba0af468631cd762258212741#/pages/83007928/simulate/sitemap). The full library is unfortunately not public.
