### ISSUE TITLE
Dead Library?

### ISSUE THREAD

**Issue by scott-joe** [mineral-ui/mineral-ui#832]
I see CA Tech was purchased by Broadcom in November and the commits dropped off significantly after that. I love that you guys have a11y concerns baked in, but as the 8ball says "Outlook not so good."

**Comment by kylegach** [comment]
Hi, Scott. The library is not dead, but you're right that it's had much, much less time devoted to it recently. We're discussing internally how best to move forward and will clearly communicate the outcome. Thank you for your kind words and concern.

_I'm going to close this for now, but will reference this issue and/or ping you when that official communication is published._

**Comment by kylegach** [comment]
We have published a document regarding the status of this project: https://github.com/mineral-ui/mineral-ui/blob/master/docs/status-of-mineral-ui.md

If you have further thoughts, please respond in the dedicated issue, #845, or to the email address available in that doc.

**Comment by scott-joe** [comment]
@kylegach Thanks for all you did for the project. I know how heartbreaking it can be to lose this amount of work. :hugs: to you and your team.
