### ISSUE TITLE
Flex Props are inconsistent

### ISSUE THREAD

**Issue by omeid** [mineral-ui/mineral-ui#834]
Greetings!

Thanks for publishing such a useful library, really like the minimal and no-nonsense approach! Kudos.

With that being said,  I find the [Flex Props](https://mineral-ui.com/components/flex#props) inconsistent and surprising.

### Expected behavior
`justifyContent` and `alignItems` should expect the standard css values, or at least accept them along with the shorthand version implemented by Mineral.

I also think the short form is less semantically correct, saying `justify content with space-between` actually makes more sense than `justify content with between` to me.

Furthermore, the short form ignores the difference of `flex-start` and `start` which are different options as per spec.
 

### Current behavior
Currently, Flex `justifyContent` accepts: `'start' | 'end' | 'center' | 'around' | 'between' | 'evenly'` instead of the [standard](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) values of `'start' | 'space-around' | 'space-between' ` et al. Same goes for `alignItems`

### Possible solution
While the idea of a shorthand is neat, I think the confusion that it creates is not worth it, most developers use auto-completion anyways.

The simplest solution would be to support the standard _long_ form of the value and possibly even deprecate the short form in the long run for the sake of simplicity.

**Comment by kylegach** [comment]
This is good feedback, @omeid. Thanks!

Would you be open to submitting a PR for this work? Here's a quick summary of changes:

- Adjust the two highlighted functions here: https://github.com/mineral-ui/mineral-ui/blob/master/src/library/Flex/styled.js#L8-L14
- Update the related constants here: https://github.com/mineral-ui/mineral-ui/blob/master/src/library/Flex/constants.js#L2-L7, which are then used for Flow types, propTypes and prop docs
- Update the relevant examples: https://github.com/mineral-ui/mineral-ui/blob/master/src/website/app/demos/Flex/Flex/examples/alignItems.js & https://github.com/mineral-ui/mineral-ui/blob/master/src/website/app/demos/Flex/Flex/examples/justifyContent.js
- Then, for consistency:
    - Apply these changes to FlexItem's `alignSelf` as well and check FlexItem and StartEnd for other necessary changes
