### ISSUE TITLE
No onChange prop for Dropdown.(I dont want to use Select)

### ISSUE THREAD

**Issue by arswaroop** [mineral-ui/mineral-ui#835]
I need to do some changes on dropdown click, but there doesnt seem to be any prop for the same. Can any one help me with this?

**Comment by brentertz** [comment]
Hi @arswaroop `Dropdowns` do not keep "selected" state like `Select` components do, so there is nothing from them to change to/from.

If you simply want to add behavior when a Dropdown item is selected, you can do so by adding an `onClick` handler in the item data.

Please see the following examples.

* https://mineral-ui.com/components/dropdown#data
* https://mineral-ui.com/components/menu#data

If, on the other hand, you do wish to keep state, consider using a `Select` component, which does have an `onChange` prop.

Hope that helps...

**Comment by arswaroop** [comment]
Awesome. I was able to use it. Thanks a lot for the information.
