### ISSUE TITLE
[Select] Select box value isnt changing.

### ISSUE THREAD

**Issue by arswaroop** [mineral-ui/mineral-ui#836]
`const data = (Carriers || []).map((carrier) => {
      const items = {};
      items.text = carrier.name;
      items.id = carrier.id;
      items.onClick = () => this.handleUpdateCarrier(carrier);
      return items;
    });
`
`
 <Select data={data} defaultSelectedItem={data[0]} size="small" />
`

When i select other options in Select, onclick is called fine but text on the Select box doesnt change.

**Comment by arswaroop** [comment]
If i put select box as a function and try to include it like this
` 
   const Selectbox = () => (
      <div>
        <Select data={data} defaultSelectedItem={data[0]} size="small" />
      </div>
    );
`
`<Selectbox />`

Then on select text doesnt change on select box.

**Comment by kylegach** [comment]
Hi, Swaroop. You closed this issue then commented again. Did you perhaps solve the first issue on your own and then the second issue is separate? If so, please create a new issue to keep the conversation focused. Thanks!

**Comment by arswaroop** [comment]
Yup thats correct. I will do a bit more work on that before submitting an issue.
