### ISSUE TITLE
[ThemedComponent]How to render Themed component

### ISSUE THREAD

**Issue by arswaroop** [mineral-ui/mineral-ui#837]
I am very new to react and mineral-ui. Please don't mind my naive query.

I have the following themed select defined. 

```jsx
const selectTheme = (theme) => {
  const k = {
    SelectContent_borderColor: theme.borderColor,
    SelectContent_backgroundColor: theme.panel_backgroundColor_inverted,
  };
  return k;
};

const selectMenu = themed(Select)(selectTheme);
```

I am not able to render this, I tried doing \<selectMenu /\>. It doesnt work.
It'll be better for noobs like me if you can provide some example project which has all the mineral-ui concepts and components implemented.

_Edited by kylegach to add proper code formatting_

**Comment by arswaroop** [comment]
I tried to do create component using below:
`const MySelect = createThemedComponent(Select, ({ theme }) => ({
  Select_backgroundColor: theme.panel_backgroundColor_inverted,
}));`
and then 
`<MySelect data={data} defaultSelectedItem={data[0]} size="small" />`

But page fails to load with this error:
![image](https://user-images.githubusercontent.com/41299771/59861501-f04fbb00-934e-11e9-8d7a-85716dcf424f.png)

**Comment by kylegach** [comment]
Hi, Swaroop.

Welcome to React, and thank you for trying Mineral UI!

I made an [annotated sandbox](https://codesandbox.io/s/themed-mineral-ui-5blk8) which should demonstrate proper usage of the `themed` function. If you are using mineral-ui v0.57 or newer, `createThemedComponent` was removed and replaced by `themed` ([more info](https://github.com/mineral-ui/mineral-ui/blob/master/docs/v0-57-migration.md#-createthemedcomponent--themed)). You used both in your code samples above, so I wrote the example sandbox for the current API.

Briefly, I think the issue in your first code sample is the lowercase component name, as components must start with an uppercase letter for use within JSX. The issue in your second, assuming you're on a current version of mineral-ui, is that `createThemedComponent` doesn't exist. Hard to help more without more details or a reproduction of the issue you can share (try forking our [starter sandbox](https://codesandbox.io/s/v410y75m0)).

Please let me know if that helped you solve your issue or if you need further assistance. Also, we don't have it documented, but here's a [sandbox demonstrating basic usage of nearly every component](https://codesandbox.io/s/wk431361n7) which may be helpful.

Finally, so we can help you effectively, please use the issue template when creating new issues in the future.

**Comment by arswaroop** [comment]
Thanks a lot Kyle for the reply.
Well last time i checked (yesterday/day before), `createThemedComponent` was still there on the website info. Anyways i got it working using the `themed` function and its wonderfully simple. I believe [this sandbox](https://codesandbox.io/s/wk431361n7 ) will all i need to complete my project. 
Thanks a lot to you and your team.

**Comment by kylegach** [comment]
Glad you got it working!

`createThemedComponent` only appears in docs & our changelog when you [search our code](https://github.com/mineral-ui/mineral-ui/search?q=createThemedComponent), which includes all of the website, so I'm not sure where you saw it recently. If you see it again, will you please share where? Thanks.
