### ISSUE TITLE
Will this project be actively developed?

### ISSUE THREAD

**Issue by jazblueful** [mineral-ui/mineral-ui#841]
Hi,

I'd like to use this beautiful library in my app, but seeing how this project hasn't had any commits in the past 5 months, it seems it is no longer being actively developed.

Can you please share your plan for this project.

Thank you

**Comment by sumitngupta** [comment]
Was going to ask the same question. I love everything about it, just hoping that the components list fills out a bit more before trying to introduce it here at work during our next design refresh. 

Awesome project!

**Comment by kylegach** [comment]
Hi, @jazblueful & @sumitngupta.

Thank you for your kind words. We've heard you and are drafting a response.

**Comment by stephane-klein** [comment]
Small up 🙏

**Comment by readeral** [comment]
@kylegach Would love that response, even if it's briefer than you hoped

**Comment by kylegach** [comment]
We have published a document regarding the status of this project: https://github.com/mineral-ui/mineral-ui/blob/master/docs/status-of-mineral-ui.md

If you have further thoughts, please respond in the dedicated issue, #845, or to the email address available in that doc.

I also want to personally apologize for taking so long to form this response. No one likes to share or receive bad news, but allowing the project to sit in limbo for so long was unprofessional and unkind to those depending on it. I'm sorry.

**Comment by sumitngupta** [comment]
No need to apologize. I completely understand how these things can go. Definitely a project to be proud of and hope someone takes it on and furthers the cause going forward. Godspeed!
